parameters:
    kaliop_queueing.driver.kinesis.class: Kaliop\Queueing\Plugins\KinesisBundle\Adapter\Kinesis\Driver
    kaliop_queueing.kinesis.queue_manager.class: Kaliop\Queueing\Plugins\KinesisBundle\Adapter\Kinesis\QueueManager
    kaliop_queueing.kinesis.message_producer.class: Kaliop\Queueing\Plugins\KinesisBundle\Adapter\Kinesis\Producer
    kaliop_queueing.kinesis.message_consumer.class: Kaliop\Queueing\Plugins\KinesisBundle\Adapter\Kinesis\Consumer

services:
    kaliop_queueing.driver.kinesis:
        class: %kaliop_queueing.driver.kinesis.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kaliop_queueing.driver, alias: kinesis }

    kaliop_queueing.kinesis.queue_manager:
        class: %kaliop_queueing.kinesis.queue_manager.class%
        #parent: kaliop_queueing.message_producer
        calls:
            - [ setContainer, [ @service_container ] ]

    kaliop_queueing.kinesis.message_producer:
        class: %kaliop_queueing.kinesis.message_producer.class%
        arguments: [ %kaliop_queueing_kinesis.default.client_config% ]

    kaliop_queueing.kinesis.message_consumer:
        class: %kaliop_queueing.kinesis.message_consumer.class%
        #arguments: [ %kaliop_queueing_kinesis.default.client_config% ]